version: "3.8"
services:
  at-dbbbm:
    build:
      context: ./dbbbm
      args:
        - BBCP_VER
        - LSST_VER
        - MNGR_VER
      network: host
    image: lsstts/dbbbm:${TAG}
    command: ["./local/etc/at_dbbbm_config.yaml"]
    environment:
      - GRP_ID
      - USR_ID
    network_mode: host
    volumes:
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: ./etc
        target: /home/mgr/local/etc
      - type: bind
        source: ${HOME}/.ssh
        target: /tmp/.ssh
        read_only: true
  cc-dbbbm:
    build:
      context: ./dbbbm
      args:
        - BBCP_VER
        - LSST_VER
        - MNGR_VER
      network: host
    image: lsstts/dbbbm:${TAG}
    command: ["./local/etc/cc_dbbbm_config.yaml"]
    environment:
      - GRP_ID
      - USR_ID
    network_mode: host
    volumes:
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: ./etc
        target: /home/mgr/local/etc
      - type: bind
        source: ${HOME}/.ssh
        target: /tmp/.ssh
        read_only: true

