database:
  engine: "sqlite:////path/to/sqlite.db"
  echo: false
  pool_type: QueuePool
handoff:
  buffer: /data/buffer
  holding: /data/holding
endpoint:
  user: jdoe
  host: endpoint.host.edu
  buffer: /data/buffer
  staging: /data/staging
  command:
    remote: "ssh {user}@{host} \"{command}\""
    transfer: "bbcp -T \"ssh -a -x -oFallBackToRsh=no %4 %I -l %U %H /home/lsstdbot/bin/bbcp\" -Z 56000:57000 {batch} {user}@{host}:{dest}"
logging:
  format: %(asctime)s:%(name)s:%(levelname)s:%(message)s
  file: transd.log
  level: INFO
general:
  chunk_size: 1
  timeout: null
  num_threads: 1
  expiration_time: 86400
  pause: 1
